### ISSUE TITLE
Notes containing sub-tags cannot be displayed

### ISSUE THREAD

**Issue by Sunny-27** [Aidurber/tag-page-preview#9] opened 2021-11-03 14:58 UTC
If a note contains multiple levels of tags (tag/sub-tag), clicking on a sub-tag does not display the corresponding list of notes.
![image](https://user-images.githubusercontent.com/69256654/140085102-d020f9b2-084d-4c87-bb54-604750bfdf91.png)

**Comment by Aidurber** [comment] 2021-11-03 15:07
Thanks for the report @Sunny-27. 

Can you clarify, are you clicking on the tag in Markdown mode or preview?

**Comment by Sunny-27** [comment] 2021-11-03 15:18
> Thanks for the report @Sunny-27.
> 
> Can you clarify, are you clicking on the tag in Markdown mode or preview?

Clicking on the tag in  whether Markdown mode or preview is the same situation (As shown in the picture)

**Comment by Aidurber** [comment] 2021-11-03 17:35
@Sunny-27  Thank you, I'll look into it when I get chance to.

**Comment by Aidurber** [comment] 2021-11-03 19:14
I'm afraid I cannot reproduce this. 
![CleanShot 2021-11-03 at 19 10 04@2x](https://user-images.githubusercontent.com/5732291/140176783-83affdc6-c45e-43fd-90ea-6098db19c5a9.jpg)

1. Are you on the latest version of this plugin?
2. Did you use the "Change tag scope" feature?


I also want to make sure we're sharing the same expectations. 

Lets say we have two pages: 
- Page 1 has `#a/b/c`
- Page 2 has `#a/b`


If you click the tag on Page 1, are you expecting Page 2 to appear here? If so, that's not how it works. `#a/b` is a completely independent tag to `#a/b/c`

**Comment by Sunny-27** [comment] 2021-11-04 02:24
> I'm afraid I cannot reproduce this. ![CleanShot 2021-11-03 at 19 10 04@2x](https://user-images.githubusercontent.com/5732291/140176783-83affdc6-c45e-43fd-90ea-6098db19c5a9.jpg)
> 
> 1. Are you on the latest version of this plugin?
> 2. Did you use the "Change tag scope" feature?
> 
> I also want to make sure we're sharing the same expectations.
> 
> Lets say we have two pages:
> 
> * Page 1 has `#a/b/c`
> * Page 2 has `#a/b`
> 
> If you click the tag on Page 1, are you expecting Page 2 to appear here? If so, that's not how it works. `#a/b` is a completely independent tag to `#a/b/c`

It is  the latest version, but I still can't show to notes containing sub-tags, as shown here：

![image](https://user-images.githubusercontent.com/69256654/140246445-2c2773bf-b668-4031-b12d-58a0f5722bdb.png)
![wemeetapp_TbKF0cUd3c](https://user-images.githubusercontent.com/69256654/140247128-ce526e6d-0f28-47cc-91fa-708f0b1bd8be.png)
![wemeetapp_6WsspRuM6Y](https://user-images.githubusercontent.com/69256654/140246968-9f3dc541-e522-4148-8e01-c8fc635cec1d.png)

**Comment by Aidurber** [comment] 2021-11-04 08:03
That's due to #6, to normalise tags. Since #Test and #test are identical in Obsidian
![CleanShot 2021-11-04 at 08 02 37@2x](https://user-images.githubusercontent.com/5732291/140278142-d65daca1-90a5-4db8-9513-9088e8565a92.jpg)


However what you've shared has led me to believe the case insensitivity has broken the page finding.

**Comment by Aidurber** [comment] 2021-11-04 08:20
@Sunny-27  this should be fixed in version 0.0.12

Thanks for your help getting to the bottom of this.

**Closed by Aidurber** 2021-11-04 08:20 UTC

**Comment by Sunny-27** [comment] 2021-11-04 13:29
> @Sunny-27 this should be fixed in version 0.0.12
> 
> Thanks for your help getting to the bottom of this.

Thanks for updating so quickly！Too much work!
